### ISSUE TITLE
V2 - À propos 

### ISSUE THREAD

**Issue by Raphaelarroche** [JulienCorb/mysterious-lowlands#3]
Je mets le mock-up sur le Drive car fichier trop gros 
https://drive.google.com/drive/u/0/folders/1-XSV0EtmQczcnMEyJfqq_nQJ9nd2dyJH

**Comment by JulienCorb** [comment]
pas trop fan de la bannière du titre avec le fond
Je trouve qu'on ne se met pas assez en valeur, peut être qu'on devrait créer une page supplémentaire uniquement dédiée à une présentation de la team (page "qui sommes-nous ?")

**Comment by Raphaelarroche** [comment]
Je vais reprendre cette partie, je reviens vers toi dès que c'est fait:) 
Ca sera sera de la modification de texte surtout donc la structure de la page sera la même

**Comment by JulienCorb** [comment]
où sont les textes ?

**Comment by JulienCorb** [comment]
ok trouvé
