### ISSUE TITLE
Pouvoir décider des créneaux de passages disponibles en fonction des différents restaurants

### ISSUE THREAD

**Issue by Clemscib** [JulienCorb/mysterious-lowlands#8]

**Comment by JulienCorb** [comment]
Si l'issue est: pouvoir moduler l'horaire d'ouverture et de fermeture le midi du resto, alors c'est fait. Tu confirmes pour que je ferme l'issue ?

**Comment by JulienCorb** [comment]
pas de réponse: je ferme.
