### ISSUE TITLE
Ajouter champ d'inscription "Entreprise / Organisation" avec "?" explicatif

### ISSUE THREAD

**Issue by Clemscib** [JulienCorb/mysterious-lowlands#9]
Remplacer le champ code promo par celui ci pour fairte moins lourd? (vu que la promo c'est le mois offert)

Texte du "?" : Renseignez ce champ afin de profiter des cadeaux et promotions offertes par/pour votre entreprise/organisation.

**Comment by JulienCorb** [comment]
on va le mettre à la place du champ "parrainage"

**Comment by JulienCorb** [comment]
update: pour l'instant on met juste "entreprise (optionnel)"
